version: '3.9'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    container_name: tawa-web
    profiles: ["web"]
  web-dev:
    build:
      context: .
      dockerfile: ./Dockerfile-Dev
    ports:
      - "8080:8080"
    environment:
      - REDIS_STRING=redis://redis:6379
    container_name: tawa-web-dev
    profiles: ["dev"]
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - "./docker/redis:/data"
    container_name: tawa-redis

